<h1>{#G-04#}</h1>

<form action="{#url#}" method="post">
<input type="hidden" name="step" value="db" />


<div class="input">
	<p>{#I-42#}</p>
</div>

<div class="input">
	<ul>
		<li>{#I-31#} : {#phpversion_server#}</li>
		<li>{#I-39#} : <strong style="color: {#phpversion_color#}">{#phpversion_current#}</strong></li>
	</ul>
</div>

<div class="input">
	<p>{#I-32#}</p>
	<ul>
		<li>{#I-33#} : {#cachecore#}</li>
		<li>{#I-34#} : {#cachemedias#}</li>
		<li>{#I-35#} : {#cachetplsc#}</li>
		<!--<li>{#I-36#} : {#incadmin_htpasswd#}</li>-->
		<li>{#I-37#} : {#incadmin_dashboard#}</li>
		<li>{#I-38#} : {#incadmin_settings#}</li>
	</ul>
<!--<input size="50" class="text" type="text" name="dir" value="{#path#}" />-->
</div>

<div class="input">
	<p class="infos">{#I-41#}</p>
</div>

<!-- begin buttons -->
<div class="input">
	<input class="button" type="submit" value="{#I-03#}" />
	<input class="button" type="button" onclick="history.go(0)" value="{#I-40#}">
</div>
<!-- end buttons -->
</form>