<h1>{#I-15#}</h1>

<form action="{#url#}" method="post">
<input type="hidden" name="step" value="cfg" />
<input type="hidden" name="dbhost" value="{#dbhost#}" />
<input type="hidden" name="dbuser" value="{#dbuser#}" />
<input type="hidden" name="dbpass" value="{#dbpass#}" />
<input type="hidden" name="dbname" value="{#dbname#}" />
<input type="hidden" name="dbprefix" value="{#dbprefix#}" />

{#message#}

<!-- begin buttons -->
<p>&nbsp;</p>
<div class="input">
	<input class="button" type="submit" value="{#button#}" />
</div>
<!-- end buttons -->
</form>