<h1>{#I-21#}</h1>

<p class="success">{#I-22#}</p>

<p></p>

<p>
	<img class="icon icons8-Support" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABEklEQVRIic2VwW3DMAxFOYJHyAgeoRvUI/xu0AFIh7cAogCPUG/QjuAN2g3qDZINkoNd14FVV4oVtAJ4EvC+RH6SRP/1gH0Ftj3Ev0CsgboyD1gcIP4TYucp2No8cLb2CpwVXpveDU5EBLE+BQ497FIFrl+/UlSwtahNtwmIe/0RLna+RaAPiCAID9zFCHRLgeEnT7U9jv0wS2FCDaBNsfD+enRpcLb3BPiqAbbDY3P/C/xtbLwOYqevtIB9FQl3JcSOQfjW7gXbw/3g4pDFGUF4aJh9xwe0KW6HDzkfCqVNAbHnGbzfBCcimoDj/IAediP8lGVTzX5wBNt+smes7aJEFtsqcVhFiagrwb5KXhZ/eS7J7ZgTWagtTQAAAABJRU5ErkJggg==" width="24" height="24">
	<a href="{#link_admin#}">{#I-60#}</a>
</p>

<p>
	<img class="icon icons8-Home" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACQ0lEQVRIie2RS0sbURiGz0/wJ+Qn9CecxXE3XgYCQhAUiiaQixIiWjJCUpy0zMpLmrgokoVBJW1WBi2KqblwiuYyMWkmrQloYy6QthKbghScz1WFJBNqaoqbHniW7/tw3g+hLh7FWEUxVnWTufeLMcxibmy8lBsbL8UYZrFnxXGWZUSWlWocB2VuXi5z83KN40BkWSnOssxfFwcx7oszzO6ZwXDZEARIT2jlzJoXMmteSE9o5YYgwJnBcJkYHn4TxLivq/LE4ODzjEZTrPM8FKbNN+KsFXL5CpxeAZxeAeTyFRBnrVCYNt/UeR4yGk0xMTBg/2MxJQSLLJurWrnrGseBqNODFDq+K25FCh2DqNPDd7sdqlbuWmRZKdrf/0RxjuTQkO/TpPZbQxAgqzfJ6SVXx+JW0ksu+Kg3yg1BgM+T2q9Ns1FCcEqtLtZ5HoqWGTlpnGqa477k8hVIGqegaJmR6zwPKbW6SAnBiBJi+2IyQUxnhOxOsOviVrI7QYjpjFAym4ESYkOUEFt0ZPRwa196cPlvtvYliI6MHlJCbAghhCzuMN6InPdMsBE5B4s7jO+O/KiCmHgCB36vIjHx5OGC0OYqVN6+UCS0udobAUReK/Jf8HiCA8fTf3vkH++Wu/+B76gMH6q/2thbd3WcaG/dpZjxHZXbBf5UDQKFn21se5wdBdsep2LGn6q1C7z0AnYLjTYCHidU/S8VCXicihkvvWgWzLmpyvIqbFPCsbDiWX5mfq+EY2HF0yk356YqhBC6BXt2yw4ZUTkPAAAAAElFTkSuQmCC" width="24" height="24">
	<a href="{#link_website#}">{#I-61#}</a>
</p>

<div class="input">
	<h3>Votre utilisateur d'administration</h3>
	<ul>
		<li>User : <strong>admin</strong></li>
		<li>Pwd : <strong>admin</strong></li>
	</ul>
</div>