<h1>{#I-01#}</h1>

<form action="{#url#}" method="post">
<input type="hidden" name="step" value="check" />

<div class="input">
	<p class="infos">{#I-45#}</p>
</div>

<div class="input"><p>{#I-02#}</p><select name='lang'><option value='0'>{#I-23#}</option>{#options#}</select></div>

<!-- begin buttons -->
<p>&nbsp;</p>
<div class="input">
	<input class="button" type="submit" value="{#I-03#}" />
</div>
<!-- end buttons -->
</form>